### ISSUE TITLE
Progress bar issue

### ISSUE THREAD

**Issue by Henthor** [dionmunk/ubersicht-now-playing#2]
First off, great little widget. Just got two small issues with it. The progress bar is all white for me, so it doesn't seem to work. Also, when I play a song in iTunes the artwork saves itself to the lib folder, which I don't want. Do you know what might cause these problems? Thanks.
![screenshot](https://cloud.githubusercontent.com/assets/27424295/25004734/12f1c2a2-2056-11e7-8be1-812571773d3b.png)

**Comment by dionmunk** [comment]
Are you using the latest versions of Ubersicht and Now Playing?

Unfortunately, saving the image is how the widget works. The AppleScript that grabs the iTunes song metadata and album artwork has to extract the image file from iTunes and save it in a location that Ubersicht can read it from. This is the only way, so far, to make the artwork possible.

**Comment by dionmunk** [comment]
Another thought, try the [Playbox](http://tracesof.net/uebersicht-widgets/#Playbox) widget and see if that works properly for you. I am using the core of Playbox to power my widget.

**Comment by Henthor** [comment]
Double checked to see if I had the latest versions, so that shouldn't be the problem. I also tried the Playbox widget as referenced, no progress bar there as well. So I'm not sure what might be wrong if it's working for you.

**Comment by dionmunk** [comment]
What version of macOS are you running @Henthor?

**Comment by Henthor** [comment]
I got sierra 10.12.4 running.

**Comment by dionmunk** [comment]
I am running Sierra 10.12.4 as well. Hmm, I don't have any other ideas. You may want to check the Github issues under Playbox and see if anyone has had something similar happen.

**Comment by Henthor** [comment]
Aight. Appreciate the quick response. I'll see if I can figure it out. :)
